### ISSUE TITLE
Ensure AMFID stays nerfed

### ISSUE THREAD

**Issue by sierrahaex** [Coalfire-Research/iOS-11.1.2-15B202-Jailbreak#1]

**Comment by sierrahaex** [comment]
This was relying on issue #7 , now that's been resolved this should be fairly straightforward.

**Comment by stek29** [comment]
@brycebearchell wait, why does amfid "nerfer" need kernel task?

**Comment by sierrahaex** [comment]
Well, it needs a task_for_port handle to AMFID. I have all the code already written as part of the jailbreak, so I wrote nerfbat to take tfp0 from hsp4, spin up a thread, and insert the exception handler (re-using the jailbreak code for nerf_amfid()). I am having problems with launchctl keeping nerfbat running, but I've made a separate issue #11  for that. Fixed in commit f10b80883ed35503730c95ecec6afd96f03f0ffa
