### ISSUE TITLE
Set hsp4

### ISSUE THREAD

**Issue by stek29** [Coalfire-Research/iOS-11.1.2-15B202-Jailbreak#7]
Since patching task_for_pid isn't an option, an alternative way of passing kernel_task is in wide use in jailbreaks.

Mach has per table and per host special ports. In XNU there's only one host though.

Host special ports can be gotten by host_get_special_port and set by host_set_special port.
However, you need host_priv to call those APIs. If youre running as root, then your mach_host_self is a host_priv (and if not -- just host)

Ports 4-7 aren't used and leave "room to grow". So, port 4 is an obvious target.
However, ports before port 7 can't be set only by kernel itself.

So, you have to set the port manually.
Ports are stored inside of "realhost" structure of type host_data_t, which has mutex in beginning and array of ipc_ports "special" after that.
So, to set host special port 4, you have to find realhost, add 0x10 (mutex) + 0x8 * 4, and write pointer to ipc_port representing tfp0 there.

And ip_kobject of host_port points to realhost :)

See coolstar/electra#22 for an example.

**Comment by sierrahaex** [comment]
Thanks for this. I'll implement this soon as the need to pass tfp0 to user space process' (like an AMFID suppression program) is high up on my list of priorities.

**Comment by sierrahaex** [comment]
Done as of 5c4fddac038a01745ffbd3f7d56d84a3e3cd30a4
