### ISSUE TITLE
Split web server

### ISSUE THREAD

**Issue by stek29** [Coalfire-Research/iOS-11.1.2-15B202-Jailbreak#8]
Web server is nice, but splitting it from the app would be great -- especially if it uses host_special_port 4.
You can pass kernel slide/address of some task to it via env/args too.
This way it might be useful for others.

**Comment by sierrahaex** [comment]
I agree. I have it currently split off, but I haven't implemented tfp0 sharing, so this will be high on the list of things for me to work on this weekend.

**Comment by sierrahaex** [comment]
Split out as of commit 81b951f8ab74da1ea2f0d739a77cf41437bca3f0
